services:
  - mongodb
matrix:
  include:
    - language: python
      python: '3.7'
      script:
        - python clean/clean.py
    - language: node
      before_script:
        - cd app
      script:
        - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: app/public
  on:
    branch: master
