language: node_js
node_js:
  - 11.14.0

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
