dist: xenial
language: python
python: '3.7'
services: mongodb
branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - nvm install 11.14.0

script:
  - python clean/clean.py
  - cd app
  - yarn
  - yarn build
  - cd public
  - echo "studentsreview.me" > CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: app/public
  on:
    branch: master
